# Generated by Django 5.1.7 on 2025-03-16 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('type', models.CharField(choices=[('Room one - Third Floor', 'Room one - Third Floor'), ('Room two - Third Floor', 'Room two - Third Floor'), ('Room one - Fourth Floor', 'Room one - Fourth Floor'), ('Room two - Fourth Floor', 'Room two - Fourth Floor')], max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending Approval'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], max_length=100)),
                ('maxOccupancy', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Room_Booking.room')),
            ],
        ),
    ]
